/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EventsEventIdImport } from './routes/events.$eventId'
import { Route as CommentsEventIdImport } from './routes/comments.$eventId'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const EventsLazyImport = createFileRoute('/events')()
const AccountLazyImport = createFileRoute('/account')()
const AboutLazyImport = createFileRoute('/about')()
const IndexMapLazyImport = createFileRoute('/_index/map')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const EventsLazyRoute = EventsLazyImport.update({
  path: '/events',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))

const AccountLazyRoute = AccountLazyImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexMapLazyRoute = IndexMapLazyImport.update({
  id: '/_index/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_index.map.lazy').then((d) => d.Route))

const EventsEventIdRoute = EventsEventIdImport.update({
  path: '/$eventId',
  getParentRoute: () => EventsLazyRoute,
} as any)

const CommentsEventIdRoute = CommentsEventIdImport.update({
  path: '/comments/$eventId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      preLoaderRoute: typeof AccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      preLoaderRoute: typeof EventsLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/comments/$eventId': {
      preLoaderRoute: typeof CommentsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof EventsLazyImport
    }
    '/_index/map': {
      preLoaderRoute: typeof IndexMapLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutLazyRoute,
  AccountLazyRoute,
  EventsLazyRoute.addChildren([EventsEventIdRoute]),
  SigninLazyRoute,
  CommentsEventIdRoute,
  IndexMapLazyRoute,
])

/* prettier-ignore-end */
